version: '3'
services:

  node-base:
    environment:
        - HOST
        - USE_SSL
    build:
      context: ../
      dockerfile: docker/base-node-dockerfile
      args:
        - HOST
        - USE_SSL
    image: 'node-base'

  node:
    environment:
      - APP_DB_USER
      - APP_DB_PASS
      - USE_SSL
      - HOST
    build:
      context: ../
      dockerfile: docker/dev-node-dockerfile
      args:
        - APP_DB_USER
        - APP_DB_PASS
        - USE_SSL
        - HOST
    ports:
      - 80:80
      - 443:443
    links:
      - mongodb
    depends_on:
      - node-base
    image: 'node:dev-1'
    volumes:
      - ..:/app

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - APP_DB_USER
      - APP_DB_PASS
    build:
      args:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
        - APP_DB_USER
        - APP_DB_PASS
      context: ../
      dockerfile: docker/mongo-dockerfile
    ports:
      - 27017:27017
    volumes:
      - mongodata-dev:/data/db
      - ../mongo-entrypoint/:/docker-entrypoint-initdb.d/
    image: 'mongodb:dev-1'

volumes:
  mongodata-dev:
